In [4]:
import numpy as np
import pandas as pd

In [5]:
print((lambda x,y : [print(i**y) for i in x])([1,2,3], 2))

1
4
9
[None, None, None]


In [6]:
x = np.array([1.5,2.7,3.2], dtype=np.int8)
x

array([1, 2, 3], dtype=int8)

In [7]:
x.size # number of elements in the array - it considers even the nested ones

3

In [8]:
m = np.array([[[1,2,3],[4,5,6]], 
              [[7,8,9],[10,11,12]]])

In [9]:
m.shape
m.ndim
m.itemsize # size of each element in bytes it's calculateed by : since shape is 2,2,3 and dtype is int64 so 2*2*3*8 = 96 bytes 


# int8 -> 1byte, int16 -> 2bytes, int32 -> 4bytes, int64 -> 8bytes
m.nbytes # total size of the array in bytes

96

In [10]:
m.dtype

dtype('int64')

In [11]:
cal = np.nan
cal

nan

In [79]:

l1 = [1,2,3]
l2 = [1,0,1]
# list_dot
# print(check(l1,l2))

In [ ]:
def dot_product(l1,l2):
      def check(l1,l2):
            # if it's 1-D
            if type(l1[0])==list and type(l2[0] == list):
                  if len(l1[0])==len(l2):
                              return True
                  else:
                              return "dimension not compatible!"
            else:
                  if len(l1)!=len(l2):
                        raise ValueError("dimension not compatible!")
                  else:
                        return False
      def dot_prod(l1,l2):
            list_dot = 0
            # for i in range(len(l1)):
            #       list_dot+=(l1[i]*l2[i])
            return sum([x*y for x,y in zip(l1,l2)])
            # return list_dot
      
      # START of dot prod
      final = []
      if len(l1) == 0 or len(l2) == 0:
            raise ValueError("empty list not allowed sarr.")

      if check(l1,l2)==True: #it's 2d array
            for i in range(len(l1)):
                  
                  lst = []
                  k =val = 0
                  while k<len(l2[0]):
                        temp = []
                        for j in range(len(l2)):
                              # print(j,k)
                              temp.append(l2[j][k])
                        k+=1
                        lst.append(temp)
                  temp=[]
                  for l in lst:
                        # print(l1[i], l)
                        temp.append(dot_prod(l1[i], l))
                  
                  final.append(temp)
            return final
      elif check(l1,l2)==False: #means it's 1-D
            return dot_prod(l1,l2)
      else:
            return check(l1,l2)
      

In [138]:
# l1 = [[1,2,1], 
#       [0,1,1],
#       [1,0,0]] 
# l2 = [[1,0], 
#       [1,0],
#       [1,1]]

import random

l1 = [random.random() for _ in range(10000)]
l2 = [random.random() for _ in range(10000)]

print(dot_product(l1,l2))
print(np.dot(l1,l2))

2490.9357337313386
2490.9357337313395


In [83]:
# dot_product raw
l1 = [[1,2,1], 
      [0,1,1],
      [1,0,0]] 
l2 = [[1,0,1], 
      [1,0,0],
      [1,1,1]]
# dot_prd = []
# for i in range(len(l1)): #i = 0
#     # net = 0
#     # #below gives the diagonal elements
#     # for j in range(len(l1[i])): #n = 2: i=1, j = 0 -> 1; i=1, j = 1
#     #     net += l1[i][j] * l2[j][i] #1*1+

#     # # for the upper traingle elements
#     # vals = 1
#     # ls = []
#     for j in range(1,len(l2)):
#         print([i,j], [j,i])
#         ls.append(l1[i][j]*l2[j][i])
#         print(ls)
#     print("rt: ", ls)
#     print(net)
#     dot_prd.append(net)

# dot_prd

In [160]:
arr = np.array([[1,2,1], 
                [0,1,1],
                [1,0,0]])

In [150]:
arr %2 ==0 #why is it giving 3 matrices? it's 

array([[False,  True, False],
       [ True, False, False],
       [False,  True,  True]])

In [ ]:
# Use of Where: np.where(condition, if true, if false)

np.where(arr%2==0, "even", "odd")

array([['odd', 'even', 'odd'],
       ['even', 'odd', 'odd'],
       ['odd', 'even', 'even']], dtype='<U4')

In [155]:
arr = np.random.rand(3,2)
display(arr.shape)
np.transpose(arr)

(3, 2)

array([[0.57027535, 0.72296388, 0.25048574],
       [0.31167973, 0.74264427, 0.51695921]])

In [ ]:
np.diag(arr)
np.diag(np.diag(arr)) #this gives only the diago other a 0

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [171]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [217]:
a = np.random.rand(3,2)
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [219]:
n = a.reshape((6,1)) #the product of the number dimension should be equal to the number of items
display(n, type(n))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

numpy.ndarray

In [226]:
n  = a.reshape((1,6,1)) #what does the 3rd parameter do? 
n.shape

(1, 6, 1)

In [249]:
# concatenate
a=  np.arange(0,6)
b = np.arange(4)
a = a.reshape((3,2))
b = b.reshape((2,2))
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[0, 1],
        [2, 3]]))

In [252]:
# for concat -> makes sure the axis concating of of same length
c = np.concat((a,b), axis = 0)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3]])

In [265]:
arr

array([[1, 2, 1],
       [0, 1, 1],
       [1, 0, 0]])

In [ ]:
arr.flatten() #from matrix to series

array([1, 2, 1, 0, 1, 1, 1, 0, 0])

In [266]:
# broadcastibng
arr*[1,2,3]

array([[1, 4, 3],
       [0, 2, 3],
       [1, 0, 0]])

In [269]:
arr.sum(axis= 0)

array([2, 3, 2])

In [274]:
a = arr
b = a
c = b.copy()
arr*=2
b,c

(array([[2, 4, 2],
        [0, 2, 2],
        [2, 0, 0]]),
 array([[1, 2, 1],
        [0, 1, 1],
        [1, 0, 0]]))

In [282]:
np.full((2,3), [1,3,5]) #the 2nd para depends on the cols

array([[1, 3, 5],
       [1, 3, 5]])

In [283]:
mat = np.random.randint(1,10,(3,3))
mat

array([[2, 7, 5],
       [5, 8, 9],
       [7, 5, 6]])

In [294]:
display(arr)
for i in np.nditer(arr, order ="A"): #order = "A" -> row basis iteration and "F" -> col basis
    print(i)

array([[2, 4, 2],
       [0, 2, 2],
       [2, 0, 0]])

2
4
2
0
2
2
2
0
0
